export const routes = {
    splash: "/",
    onboarding: "/(auth)/onboarding",
    login: "/(auth)/login",
    verifyOtp: "/(auth)/verify-otp",
    home: "/(tabs)/home",
    jobs: "/(tabs)/jobs",
    messages: "/(tabs)/messages",
    profile: "/(tabs)/profile",
    categories: "/categories",
    category: (id: string) => `/category/${id}`,
    artisan: (id: string) => `/artisan/${id}`,
    job: (id: string) => `/job/${id}`,
    jobRequest: "/job/request",
    jobReview: "/job/review",
    search: "/search",
    notifications: "/notifications",
    chat: (id: string) => `/chat/${id}`,
    refer: "/refer",
    settings: "/settings",
    editProfile: "/edit-profile",
    help: "/help",
    saved: "/saved",
} as const;
